
# Allow the function to be called from the browser
allowed_http_methods = ["POST", "OPTIONS"]

# Allow specific secrets to be accessible to this function
[secrets]
TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN"
TWILIO_PHONE_NUMBER = "TWILIO_PHONE_NUMBER"
