// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upffcxqiozqhdgfesmji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZmZjeHFpb3pxaGRnZmVzbWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxODU4NTcsImV4cCI6MjA1Mzc2MTg1N30.RNkakuJDMiO4bvN7Y1p-NlZYHr5obgOnDcwLQMdElLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Force redirect mode for all OAuth providers to prevent iframe issues
    detectSessionInUrl: true,
    persistSession: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    flowType: 'pkce',
    debug: process.env.NODE_ENV === 'development'
  },
  global: {
    headers: {
      'X-Client-Info': 'sideby-web-client'
    }
  }
});